spring.application.name=job-scheduler
spring.datasource.url=jdbc:postgresql://localhost:5432/job_scheduler
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=${DB_PASSWORD}
